name: Build GraalVM Native Image

on: [push, pull_request]

jobs:
  build:
    name: Build Native Image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'  # GraalVM version compatible with your build
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build Spring Boot Native Image
        run: mvn -Pnative -DskipTests=true native:compile

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: nh-sc-springboot-${{ matrix.os }}
          path: target/nh-sc-springboot
