name: Build GraalVM Native Image

on: [push, pull_request]

jobs:
  build:
    name: Build Native Image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Setup GraalVM
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'  # GraalVM version compatible with your build
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      # Step 5: Build Native Image
      - name: Build Spring Boot Native Image
        run: mvn -Pnative -DskipTests=true native:compile

      # Step 6: Upload Binary
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-native-${{ matrix.os }}
          path: target/*-native
